# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.14.3
    hooks:
      # options: stylua (from cargo) or stylua-github (from GitHub)
      - id: stylua-system
        args: ["--config-path", "nvim/.stylua.toml"]
