[server]
follow_symlink = false
browser = "default"

[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]

[display]
cell_output = "below"
default_table_page_size = 50
default_width = "full"
theme = "light"
default_table_max_columns = 50
reference_highlighting = true
dataframes = "rich"
code_editor_font_size = 14

[runtime]
dotenv = []
auto_reload = "autorun"
default_auto_download = []
on_cell_change = "autorun"
output_max_bytes = 8000000
std_stream_max_bytes = 1000000
auto_instantiate = true
watcher_on_save = "lazy"
default_sql_output = "native"
reactive_tests = true
default_csv_encoding = "utf-8"

[experimental]
external_agents = true
multi_column = true
tracing = true
chat_sidebar = true

[ai]
rules = ""
mode = "manual"
inline_tooltip = false

[ai.models]
custom_models = []
displayed_models = []

[ai.open_ai]

[ai.bedrock]

[ai.custom_providers]

[ai.anthropic]

[ai.google]

[formatting]
line_length = 79

[mcp]
presets = []

[mcp.mcpServers]

[package_management]
manager = "uv"

[diagnostics]
sql_linter = true
enabled = true

[language_servers.pyrefly]
enabled = false

[language_servers.pylsp]
enable_pylint = false
enable_pyflakes = false
enable_ruff = false
enable_flake8 = false
enable_mypy = false
enabled = false
enable_pydocstyle = false

[language_servers.basedpyright]

[language_servers.ty]
enabled = false

[snippets]
custom_paths = []
include_default_snippets = true

[completion]
copilot = false
activate_on_typing = true
signature_hint_on_typing = true

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = true
