return {
  icons = {
    diagnostics = {
      Error = ' ',
      Warn = ' ',
      Hint = ' ',
      Info = ' ',
    },
    git = {
      added = ' ',
      modified = ' ',
      removed = ' ',
    },
    kinds = {
      Array = ' ',
      Boolean = ' ',
      Class = ' ',
      Color = ' ',
      Copilot = ' ',
      Constant = ' ',
      Constructor = ' ',
      Enum = ' ',
      EnumMember = ' ',
      Event = ' ',
      Field = 'ﰠ ',
      File = ' ',
      Folder = ' ',
      Function = ' ',
      Interface = ' ',
      Key = ' ',
      Keyword = ' ',
      Method = ' ',
      Module = ' ',
      Namespace = ' ',
      Null = 'ﳠ ',
      Number = ' ',
      Object = ' ',
      Operator = ' ',
      Package = ' ',
      Property = 'ﰠ ',
      Reference = ' ',
      Snippet = ' ',
      String = ' ',
      Struct = 'פּ',
      Text = ' ',
      TypeParameter = ' ',
      Unit = '塞',
      Value = ' ',
      Variable = ' ',
    },
  },
}
