cache_dir = "/Users/luca/.cache/pdm"

[global_project]
path = "/Users/luca/.local/state/pdm/global-project"

[venv]
location = "/Users/luca/.local/state/pdm/venvs"

[python]
use_pyenv = false

[repository]
[repository.testpypi]
url = "https://test.pypi.org/legacy/"
username = "__token__"

[repository.pypi]
url = "https://upload.pypi.org/legacy/"
username = "__token__"
