-- h: visual-multi
-- n            find next
-- N            find previous
-- q            skip and find next (or previous if searching backwards)
-- Q            remove current region and go to previous
-- ]            go to next
-- [            go to previous
-- <C-f>        go to next (by page)
-- <C-b>        go to previous (by page)
