#! /usr/bin/env zsh

main () {
    RELOAD="reload:zoxide query --list --score --exclude "$PWD""
    PREVIEW="eza --all --group-directories-first --color=always --icons --oneline --level=2 --tree -- {2..}"
    fzf \
        --no-sort \
        --tmux=80% \
        --border=none \
        --bind="start:$RELOAD" \
        --bind="ctrl-/:toggle-preview" \
        --bind="enter:become:echo {2..}" \
        --preview="$PREVIEW" \
        --preview-window="up" \
        --query="${*:-}"
}

main "${*:-}"
